[package]
name = "double-skunk-rust"
version = "0.1.0"
authors = ["loboyd <logan.boyd@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termion = "1.5"
rand = "0.5"
